servers:

  operation-servers:
    own-oam:
      basic:
        - service-name: /v1/register-yourself
          uuid: mm-1-0-0-op-s-bm-000
        - service-name: /v1/embed-yourself
          uuid: mm-1-0-0-op-s-bm-001
        - service-name: /v1/redirect-service-request-information
          uuid: mm-1-0-0-op-s-bm-002
        - service-name: /v1/redirect-oam-request-information
          uuid: mm-1-0-0-op-s-bm-003
        - service-name: /v1/end-subscription
          uuid: mm-1-0-0-op-s-bm-004
        - service-name: /v1/inquire-oam-request-approvals
          uuid: mm-1-0-0-op-s-bm-005
        - service-name: /v1/update-client
          uuid: mm-1-0-0-op-s-bm-007
        - service-name: /v1/list-ltps-and-fcs
          uuid: mm-1-0-0-op-s-bm-008
        - service-name: /v1/redirect-topology-change-information
          uuid: mm-1-0-0-op-s-bm-009
        - service-name: /v1/update-operation-key
          uuid: mm-1-0-0-op-s-bm-010
        - service-name: /v1/update-operation-client
          uuid: mm-1-0-0-op-s-bm-011
      individual:
        - service-name: /v1/bequeath-your-data-and-die
          uuid: mm-1-0-0-op-s-im-000
    service:
      basic:
        - service-name: /v1/inform-about-application
          uuid: mm-1-0-0-op-s-bs-001
        - service-name: /v1/inform-about-application-in-generic-representation
          uuid: mm-1-0-0-op-s-bs-002
        - service-name: /v1/inform-about-release-history
          uuid: mm-1-0-0-op-s-bs-003
        - service-name: /v1/inform-about-release-history-in-generic-representation
          uuid: mm-1-0-0-op-s-bs-004
      individual:
        - service-name: /v1/start-application-in-generic-representation
          uuid: mm-1-0-0-op-s-is-000
          # Services specific to this application
        - service-name: /v1/provide-mediator
          uuid: mm-1-0-0-op-s-is-001
        - service-name: /v1/provide-mediator-ip
          uuid: mm-1-0-0-op-s-is-002
           
  http-server:
    own-application-name: MediatorManager
    own-release-number: 1.0.0
    uuid: mm-1-0-0-http-s-bm-000
  tcp-server:
    own-ip-address: 1.1.4.6 
    own-tcp-port: 4006
    uuid: mm-1-0-0-tcp-s-bm-000



clients:

  - http-client:
      application-name: OldRelease
      release-number: 1.0.0
      uuid: mm-1-0-0-http-c-bm-or-1-0-0-000
    tcp-client:
      ip-address: 1.1.4.6
      tcp-port: 4006
      uuid: mm-1-0-0-tcp-c-bm-or-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/bequeath-your-data-and-die
            uuid: mm-1-0-0-op-c-bm-or-1-0-0-000
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number: 1.0.0
      uuid: mm-1-0-0-http-c-bm-nr-1-0-0-000
    tcp-client:
      ip-address: 1.1.4.6
      tcp-port: 4006
      uuid: mm-1-0-0-tcp-c-bm-nr-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          ##Done: Add Services required for handing-over configuration or data during update
      service:
        basic:
        individual:

  - http-client:
      application-name: RegistryOffice
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-bm-ro-2-0-0-000
    tcp-client:
      ip-address: 1.1.3.8
      tcp-port: 3008
      uuid: mm-1-0-0-tcp-c-bm-ro-2-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/register-application
            uuid: mm-1-0-0-op-c-bm-ro-2-0-0-000
          - service-name: /v1/relay-server-replacement
            uuid: mm-1-0-0-op-c-bm-ro-2-0-0-001
          - service-name: /v1/deregister-application
            uuid: mm-1-0-0-op-c-bm-ro-2-0-0-002
          - service-name: /v1/relay-operation-update
            uuid: mm-1-0-0-op-c-bm-ro-2-0-0-003
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: TypeApprovalRegister
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-is-tar-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.9 
      tcp-port: 3009
      uuid: mm-1-0-0-tcp-c-is-tar-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: ExecutionAndTraceLog
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-bm-eatl-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.10
      tcp-port: 3010
      uuid: mm-1-0-0-tcp-c-bm-eatl-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/record-service-request
            uuid: mm-1-0-0-op-c-bm-eatl-1-0-0-000
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: OamLog
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-bm-ol-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.11
      tcp-port: 3011
      uuid: mm-1-0-0-tcp-c-bm-ol-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/record-oam-request
            uuid: mm-1-0-0-op-c-bm-ol-1-0-0-000
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: AdministratorAdministration
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-bm-aa-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.12
      tcp-port: 3012
      uuid: mm-1-0-0-tcp-c-bm-aa-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/approve-oam-request
            uuid: mm-1-0-0-op-c-bm-aa-1-0-0-000
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: ApplicationLayerTopology
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-bm-alt-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.13
      tcp-port: 3013
      uuid: mm-1-0-0-tcp-c-bm-alt-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/update-all-ltps-and-fcs
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-000
          - service-name: /v1/update-ltp
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-001
          - service-name: /v1/delete-ltp-and-dependents
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-002
          - service-name: /v1/update-fc
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-003
          - service-name: /v1/update-fc-port
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-004
          - service-name: /v1/delete-fc-port
            uuid: mm-1-0-0-op-c-bm-alt-1-0-0-005
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: OperationKeyManagement
      release-number: 2.0.0
      uuid: mm-1-0-0-http-c-is-okm-1-0-0-000
    tcp-client:
      ip-address: 1.1.3.14
      tcp-port: 3014
      uuid: mm-1-0-0-tcp-c-is-okm-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application

  - http-client:
      application-name: ## done: Add Name of application to be addressed
      release-number: ## done: Add Release number of application to be addressed
      uuid: ## done: Add UUID of the HttpClient
    tcp-client:
      ip-address: ## done: Add IP address of application to be addressed
      tcp-port: ## done: Add TCP port of application to be addressed
      uuid: ## done: Add UUID of the TcpClient
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          ## done: Add Clients specific to this application, but addressing all other applications
        individual:
          ## done: Add Clients specific to this application
